MyHotkeySettingsGui := Gui()
MyHotkeySettingsGui.OnEvent("Close", (*) => ReEnableGui(MySettingsGui))
MyHotkeySettingsGui.Opt("+AlwaysOnTop")
MyHotkeySettingsGui.Title := SETTINGS_SCRIPT_TITLE

MyHotkeySettingsGui.AddText(, 'Hotkey for "Drop BST" :')
HotkeyBST_HotkeyEdit := MyHotkeySettingsGui.AddEdit("w100 Limit17", DEFAULT_HOTKEY_BST)
HotkeyBST_HotkeyEdit.OnEvent("Focus", (*) => OnEdit_Focus(HotkeyBST_ApplyButton))
HotkeyBST_HotkeyEdit.OnEvent("LoseFocus", (*) => OnEdit_LoseFocus(HotkeyBST_HotkeyEdit, HotkeyBST_ApplyButton, Hotkeys_Map["HotkeyBST"]))
HotkeyBST_ApplyButton := MyHotkeySettingsGui.AddButton("w66 x+10", "Apply")
HotkeyBST_ApplyButton.OnEvent("Click", (*) => ApplyHotkey("HotkeyBST"))
HotkeyBST_ResetButton := MyHotkeySettingsGui.AddButton("w66 x+10", "Reset")
HotkeyBST_ResetButton.OnEvent("Click", (*) => ResetHotkey("HotkeyBST"))
HotkeyBST_ToggleButton := MyHotkeySettingsGui.AddButton("w66 x+10", "Disable")
HotkeyBST_ToggleButton.OnEvent("Click", (*) => ToggleHotkey("HotkeyBST"))
MyHotkeySettingsGui.AddText("x10", 'Hotkey for "Reload All Weapons" :')
HotkeyReload_HotkeyEdit := MyHotkeySettingsGui.AddEdit("w100 Limit17", DEFAULT_HOTKEY_RELOAD)
HotkeyReload_HotkeyEdit.OnEvent("Focus", (*) => OnEdit_Focus(HotkeyReload_ApplyButton))
HotkeyReload_HotkeyEdit.OnEvent("LoseFocus", (*) => OnEdit_LoseFocus(HotkeyReload_HotkeyEdit, HotkeyReload_ApplyButton, Hotkeys_Map["HotkeyReload"]))
HotkeyReload_ApplyButton := MyHotkeySettingsGui.AddButton("w66 x+10", "Apply")
HotkeyReload_ApplyButton.OnEvent("Click", (*) => ApplyHotkey("HotkeyReload"))
HotkeyReload_ResetButton := MyHotkeySettingsGui.AddButton("w66 x+10", "Reset")
HotkeyReload_ResetButton.OnEvent("Click", (*) => ResetHotkey("HotkeyReload"))
HotkeyReload_ToggleButton := MyHotkeySettingsGui.AddButton("w66 x+10", "Disable")
HotkeyReload_ToggleButton.OnEvent("Click", (*) => ToggleHotkey("HotkeyReload"))
MyHotkeySettingsGui.AddText("x10", 'Hotkey for "Spam Respawn" :')
HotkeySpamRespawn_HotkeyEdit := MyHotkeySettingsGui.AddEdit("w100 Limit17", DEFAULT_HOTKEY_SPAMRESPAWN)
HotkeySpamRespawn_HotkeyEdit.OnEvent("Focus", (*) => OnEdit_Focus(HotkeySpamRespawn_ApplyButton))
HotkeySpamRespawn_HotkeyEdit.OnEvent("LoseFocus", (*) => OnEdit_LoseFocus(HotkeySpamRespawn_HotkeyEdit, HotkeySpamRespawn_ApplyButton, Hotkeys_Map["HotkeySpamRespawn"]))
HotkeySpamRespawn_ApplyButton := MyHotkeySettingsGui.AddButton("w66 x+10", "Apply")
HotkeySpamRespawn_ApplyButton.OnEvent("Click", (*) => ApplyHotkey("HotkeySpamRespawn"))
HotkeySpamRespawn_ResetButton := MyHotkeySettingsGui.AddButton("w66 x+10", "Reset")
HotkeySpamRespawn_ResetButton.OnEvent("Click", (*) => ResetHotkey("HotkeySpamRespawn"))
HotkeySpamRespawn_ToggleButton := MyHotkeySettingsGui.AddButton("w66 x+10", "Disable")
HotkeySpamRespawn_ToggleButton.OnEvent("Click", (*) => ToggleHotkey("HotkeySpamRespawn"))
MyHotkeySettingsGui.AddText("x10", 'Hotkey for "Thermal Vision" :')
HotkeyThermalVision_HotkeyEdit := MyHotkeySettingsGui.AddEdit("w100 Limit17", DEFAULT_HOTKEY_THERMALVISION)
HotkeyThermalVision_HotkeyEdit.OnEvent("Focus", (*) => OnEdit_Focus(HotkeyThermalVision_ApplyButton))
HotkeyThermalVision_HotkeyEdit.OnEvent("LoseFocus", (*) => OnEdit_LoseFocus(HotkeyThermalVision_HotkeyEdit, HotkeyThermalVision_ApplyButton, Hotkeys_Map["HotkeyThermalVision"]))
HotkeyThermalVision_ApplyButton := MyHotkeySettingsGui.AddButton("w66 x+10", "Apply")
HotkeyThermalVision_ApplyButton.OnEvent("Click", (*) => ApplyHotkey("HotkeyThermalVision"))
HotkeyThermalVision_ResetButton := MyHotkeySettingsGui.AddButton("w66 x+10", "Reset")
HotkeyThermalVision_ResetButton.OnEvent("Click", (*) => ResetHotkey("HotkeyThermalVision"))
HotkeyThermalVision_ToggleButton := MyHotkeySettingsGui.AddButton("w66 x+10", "Disable")
HotkeyThermalVision_ToggleButton.OnEvent("Click", (*) => ToggleHotkey("HotkeyThermalVision"))
MyHotkeySettingsGui.AddText("x10", 'Hotkey for "Suspend Game" :')
HotkeySuspendGame_HotkeyEdit := MyHotkeySettingsGui.AddEdit("w100 Limit17", DEFAULT_HOTKEY_SUSPENDGAME)
HotkeySuspendGame_HotkeyEdit.OnEvent("Focus", (*) => OnEdit_Focus(HotkeySuspendGame_ApplyButton))
HotkeySuspendGame_HotkeyEdit.OnEvent("LoseFocus", (*) => OnEdit_LoseFocus(HotkeySuspendGame_HotkeyEdit, HotkeySuspendGame_ApplyButton, Hotkeys_Map["HotkeySuspendGame"]))
HotkeySuspendGame_HotkeyEdit.Enabled := false
HotkeySuspendGame_ApplyButton := MyHotkeySettingsGui.AddButton("w66 x+10", "Apply")
HotkeySuspendGame_ApplyButton.OnEvent("Click", (*) => ApplyHotkey("HotkeySuspendGame"))
HotkeySuspendGame_ApplyButton.Enabled := false
HotkeySuspendGame_ResetButton := MyHotkeySettingsGui.AddButton("w66 x+10", "Reset")
HotkeySuspendGame_ResetButton.OnEvent("Click", (*) => ResetHotkey("HotkeySuspendGame"))
HotkeySuspendGame_ResetButton.Enabled := false
HotkeySuspendGame_ToggleButton := MyHotkeySettingsGui.AddButton("w66 x+10", "Enable")
HotkeySuspendGame_ToggleButton.OnEvent("Click", (*) => ToggleHotkey("HotkeySuspendGame"))
MyHotkeySettingsGui.AddText("x10", 'Hotkey for "Terminate Game" :')
HotkeyTerminateGame_HotkeyEdit := MyHotkeySettingsGui.AddEdit("w100 Limit17", DEFAULT_HOTKEY_TERMINATEGAME)
HotkeyTerminateGame_HotkeyEdit.OnEvent("Focus", (*) => OnEdit_Focus(HotkeyTerminateGame_ApplyButton))
HotkeyTerminateGame_HotkeyEdit.OnEvent("LoseFocus", (*) => OnEdit_LoseFocus(HotkeyTerminateGame_HotkeyEdit, HotkeyTerminateGame_ApplyButton, Hotkeys_Map["HotkeyTerminateGame"]))
HotkeyTerminateGame_HotkeyEdit.Enabled := false
HotkeyTerminateGame_ApplyButton := MyHotkeySettingsGui.AddButton("w66 x+10", "Apply")
HotkeyTerminateGame_ApplyButton.OnEvent("Click", (*) => ApplyHotkey("HotkeyTerminateGame"))
HotkeyTerminateGame_ApplyButton.Enabled := false
HotkeyTerminateGame_ResetButton := MyHotkeySettingsGui.AddButton("w66 x+10", "Reset")
HotkeyTerminateGame_ResetButton.OnEvent("Click", (*) => ResetHotkey("HotkeyTerminateGame"))
HotkeyTerminateGame_ResetButton.Enabled := false
HotkeyTerminateGame_ToggleButton := MyHotkeySettingsGui.AddButton("w66 x+10", "Enable")
HotkeyTerminateGame_ToggleButton.OnEvent("Click", (*) => ToggleHotkey("HotkeyTerminateGame"))
HotkeysHelp_Link := MyHotkeySettingsGui.AddLink("x10", 'Full list of possible hotkey inputs:`n<a id="KeyListHelp" href="https://www.autohotkey.com/docs/v2/KeyList.htm">https://www.autohotkey.com/docs/v2/KeyList.htm</a>')
HotkeysHelp_Link.OnEvent("Click", Link_Click)
