Hotkeys_Map := Map(
    "HotkeyBST", DEFAULT_HOTKEY_BST,
    "HotkeyReload", DEFAULT_HOTKEY_RELOAD,
    "HotkeySpamRespawn", DEFAULT_HOTKEY_SPAMRESPAWN,
    "HotkeyThermalVision", DEFAULT_HOTKEY_THERMALVISION,
    "HotkeySuspendGame", DEFAULT_HOTKEY_SUSPENDGAME,
    "HotkeyTerminateGame", DEFAULT_HOTKEY_TERMINATEGAME
)
KeyHold := KEY_DELAY_DEFAULT
KeyDelay := KEY_DELAY_DEFAULT
IsMacroRunning := false
HasDisplayedMacroSpeedWarning1 := false
HasDisplayedMacroSpeedWarning2 := false
gtaWindowID := 0
EditReloadAllWeapons := DEFAULT_EDIT_RELOAD_All_WEAPONS
KeyBindings_Map := Map(
    "Interaction_Menu", DEFAULT_KEY_BINDING__INTERACTION_MENU
)
prevX := prevY := prevW := prevH := -1
DefaultSettings_Map := Map(
    "EDIT_RELOAD_All_WEAPONS", DEFAULT_EDIT_RELOAD_All_WEAPONS,
    "KEY_BINDING__INTERACTION_MENU", DEFAULT_KEY_BINDING__INTERACTION_MENU,
    "HOTKEY_BST", DEFAULT_HOTKEY_BST,
    "HOTKEY_RELOAD", DEFAULT_HOTKEY_RELOAD,
    "HOTKEY_SPAMRESPAWN", DEFAULT_HOTKEY_SPAMRESPAWN,
    "HOTKEY_THERMALVISION", DEFAULT_HOTKEY_THERMALVISION,
    "HOTKEY_SUSPENDGAME", DEFAULT_HOTKEY_SUSPENDGAME,
    "HOTKEY_TERMINATEGAME", DEFAULT_HOTKEY_TERMINATEGAME,
    "KEY_DELAY", KEY_DELAY_DEFAULT
)
Settings_Map := DefaultSettings_Map
